### ISSUE TITLE
Error, but plays track

### ISSUE THREAD

**Issue by timonvanhasselt** [OpenVoiceOS/skill-ovos-youtube#27]
"Can't play" message but the audio is played (I think after 10 seconds, normally sooner).
I don't see any recent pytube changes, but maybe it's not up to date anymore with the YouTube urls?

Error:

```
2024-10-04 13:33:56.650 - skills - ovos_utils.file_utils:resolve_resource_file:194 - WARNING - Deprecation version=0.1.0. Caller=ovos_utils.dialog:166. Expected a dict config and got None.
2024-10-04 13:33:56.657 - skill-ovos-youtube.openvoiceos - ERROR - Exception while accessing title of https://youtube.com/watch?v=9EPTNgPZxw0. Please file a bug report at https://github.com/pytube/pytube
Traceback (most recent call last):
  File "/home/ovos/.venvs/ovos/lib/python3.11/site-packages/tutubo/pytube/__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ovos/.venvs/ovos/lib/python3.11/site-packages/ovos_utils/events.py", line 78, in wrapper
    handler(message)
  File "/home/ovos/.venvs/ovos/lib/python3.11/site-packages/ovos_workshop/skills/common_play.py", line 492, in __handle_ocp_query
    for r in results:
  File "/home/ovos/.venvs/ovos/lib/python3.11/site-packages/skill_ovos_youtube/__init__.py", line 119, in search_youtube
    if "patreon" in v.title.lower():  # TODO blacklist.voc
                    ^^^^^^^
  File "/home/ovos/.venvs/ovos/lib/python3.11/site-packages/tutubo/pytube/__main__.py", line 348, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=9EPTNgPZxw0. Please file a bug report at https://github.com/pytube/pytube
```

**Comment by MenneBos** [comment]
I commented out line 119 and 120 of __init__.py, to revolve the issue, because the error is spoken out loud by OVOS through the music.
